### PR TITLE
Code normalization of geo-graindirstruct branch

### PR DESCRIPTION
**Pull request by jdom**
Mostly code cleanup and 1 potential behavioral change fix (reverted behavior to what it was before and avoids throwing a null ref exception).
Let me know it you want me to squash them all into 1 commit. I kept them separate to keep the diffs very simple for review.

### CODE REVIEW

**Comment by sebastianburckhardt** [comment]
I don't particularly care whether it is 1 commit or not. But I think the Orleans main repo cares? Once I pull this  into geo-graindirstruct it will no longer be easy to squash (because of all the other dependent branches) so perhaps it is better to squash it now, before I pull it in.

**Comment by sebastianburckhardt** [comment]
BTW, the changes look good to me. Thanks!

(The renaming of the MultiClusterStatus constants will require a bit of adjustment in the branch geo_globalsingleinstance but that's not difficult)

**Comment by jdom** [comment]
Ok, I did squash some commits. Nevertheless I think we are going to take your suggestion and create branches in the main Orleans repo... those branches will have the commits squashed

**Comment by jdom** [comment]
What I meant is, feel free to just merge

**Comment by sebastianburckhardt** [comment]
I have pulled this, and also propagated it to VSOnline.
I have also propagated the name changes to the geo_globalsingleinstance branch.

**Pull request merged**
